// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrilcyigogtjmjykutzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZyaWxjeWlnb2d0am1qeWt1dHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyOTA2NTgsImV4cCI6MjA3MTg2NjY1OH0.lgeoDPNGACHzVLk3po44tch3Rgoi2X7I_n8ZuXNqKvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});